print("Tipo int:", 1, "=>", type(1))
print("Tipo float:", 1.0, "=>", type(1.0))
print("Tipo str:", "string", "=>", type("string"))
print("Tipo bool:", True, "=>", type(True))
print("Tipo list:", [1, 2, 3], "=>", type([1, 2, 3]))